#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

GIT_USER=$(git config user.name)
GIT_EMAIL=$(git config user.email)
COMMIT_MSG_FILE=$1

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false -c diff.noprefix=false --no-pager diff --raw -r -p -m -M --full-index --no-color --staged | cat)

# Grumphp env vars

export GRUMPHP_GIT_WORKING_DIR="$(git rev-parse --show-toplevel)"

cd "${GRUMPHP_GIT_WORKING_DIR}" || exit 1

GRUMPHP_CONFIG_FILE=''
DEVTOOLS_GRUMPHP_CONFIG=__DEV_TOOLS_GRUMPHP_CONFIG__

if [ -f './grumphp.yml' ]; then
  GRUMPHP_CONFIG_FILE='./grumphp.yml'
elif [ -f "${DEVTOOLS_GRUMPHP_CONFIG}" ]; then
  GRUMPHP_CONFIG_FILE="${DEVTOOLS_GRUMPHP_CONFIG}"
fi

# Run GrumPHP
if [ -x "vendor/bin/grumphp" ]; then
  GRUMPHP_COMMAND='vendor/bin/grumphp'
elif [ -x "vendor/bin/grumphp.phar" ]; then
  GRUMPHP_COMMAND='vendor/bin/grumphp.phar'
else
  GRUMPHP_COMMAND='grumphp'
fi

if [ -n "${GRUMPHP_COMMAND}" ]; then
  if [ -n "${GRUMPHP_CONFIG_FILE}" ]; then
    printf "%s\n" "${DIFF}" | exec "${GRUMPHP_COMMAND}" '--config' "${GRUMPHP_CONFIG_FILE}" 'git:commit-msg' "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE"
  else
    printf "%s\n" "${DIFF}" | exec "${GRUMPHP_COMMAND}" 'git:commit-msg' "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE"
  fi
fi
