#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false -c diff.noprefix=false --no-pager diff --raw -r -p -m -M --full-index --no-color --staged | cat)

# Grumphp env vars

export GRUMPHP_GIT_WORKING_DIR="$(git rev-parse --show-toplevel)"

cd "${GRUMPHP_GIT_WORKING_DIR}" || exit 1

GRUMPHP_CONFIG_FILE=''
DEVTOOLS_GRUMPHP_CONFIG=__DEV_TOOLS_GRUMPHP_CONFIG__

if [ -f './grumphp.yml' ]; then
  GRUMPHP_CONFIG_FILE='./grumphp.yml'
elif [ -f "${DEVTOOLS_GRUMPHP_CONFIG}" ]; then
  GRUMPHP_CONFIG_FILE="${DEVTOOLS_GRUMPHP_CONFIG}"
fi

# Run GrumPHP
if [ -n "${GRUMPHP_CONFIG_FILE}" ]; then
  printf "%s\n" "${DIFF}" | exec 'vendor/bin/grumphp.phar' '--config' "${GRUMPHP_CONFIG_FILE}" 'git:pre-commit' '--skip-success-output'
fi

printf "%s\n" "${DIFF}" | exec 'vendor/bin/grumphp.phar' 'git:pre-commit' '--skip-success-output'
