name: "Fast Forward Test Suite"

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    uses: php-fast-forward/dev-tools/.github/workflows/tests.yml@main
    secrets: inherit
