name: Run PHPUnit Tests

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [ "main" ]

permissions:
    contents: write
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    tests:
        name: Run Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [ '8.3', '8.4', '8.5' ]
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
                ref: ${{ github.head_ref || github.ref_name }}

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Install dependencies
              uses: php-actions/composer@v6
              env:
                  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ github.token }}"} }'
              with:
                  php_version: ${{ matrix.php-version }}

            - name: Run PHPUnit tests
              uses: php-actions/composer@v6
              with:
                php_version: ${{ matrix.php-version }}
                php_extensions: pcov
                command: 'dev-tools'
                args: 'tests --coverage=./public/coverage'

            - name: Ensure minimum code coverage
              run: php vendor/bin/phpunit-coverage-check --min=80 ./public/coverage/clover.xml
