name: Maintain Wiki

on:
  workflow_dispatch:
  schedule:
    - cron: '17 3 * * *'
  pull_request_target:
    types: [closed]

concurrency:
  group: update-wiki-maintenance-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  maintenance:
    permissions:
      contents: write
      pull-requests: read
    uses: ./.github/workflows/wiki-maintenance.yml
    secrets: inherit
