name: Update Wiki

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: update-wiki-preview-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    permissions:
      actions: write
      contents: write
      pull-requests: read
    uses: ./.github/workflows/wiki-preview.yml
    secrets: inherit
